server:
  port: 8091
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://192.168.1.166:3306/admin?useUnicode=true&characterEncoding=UTF-8&useSSL=true&&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    #      #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1

    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat, wall

  redis:
    host: 127.0.0.1
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.163.com
    username: 13006382305@163.com
    password: zx19930724

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zhongye.manager.module.*.dao
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  config: src/main/resources/logback-spring.xml
  level:
    com.zhongye.manager.module.*.dao: debug