server:
  port: 8091

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  type-aliases-package: com.igeek.admin.dao
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  config: classpath:logback-spring.xml
  level:
    com.igeek.admin.dao: debug

spring:
  profiles:
    active: dev