spring:
  profiles:
    active: dev

server:
  port: 8101
  servlet:
    context-path: /ums

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.igeek.cloudclass.ums.mapper
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  config: classpath:logback-spring.xml
  level:
    com.igeek.cloudclass.task.dao: debug